AccountIsBlocked = "Unfortunately, your account is blocked!"
AccountIsDeleted = "Unfortunately, your account is blocked and will be deleted in 1 month!"
AccountIsPending = "Your account is not yet activated! Please try again later..."
AccountIsRejected = "Unfortunately, your account registration request has been rejected!"
CodeSuccessfullyAddeded = "Code successfully addeded"
CouldNotRefreshAccessToken = "Could not refresh access token"
ErrorAttemptExceeded = "Number of code entry attempts exceeded. Please come back later..."
HelloPerson = "Hello {{.Name}}"
HttpStatusForbidden = "You do not have access to perform this operation"
InvalidEmailOrPassword = "Invalid email or password"
InvalidOtpCode = "Invalid Otp Code!"
LogoutSuccessful = "Logout Successful"
MessageOtpCode = "Hello, <b>{{.Customer}}</b>!<br />Code: <b>{{.OtpCode}}</b>!<br />Copy it and paste it into the field for verification.<br />Don't show this code to anyone!<hr><small><i>Best regards, team my-domain!</small></i>"
PasswordDoNotMatch = "Password do not match!"
RegisterUserConglaturation = "Congratulations! Your account has been successfully created!"
SavedSuccessfully = "Saved successfully!"
ServerStatusMethodNotAllowed = "Method not allowed!"
SometingWentWrongServer = "Something went wrong on the server"
SubjectOtpCode = "Your verification code: {{.OtpCode}}"
TheUserBelongingToThisTokenNoLoggerExists = "The user belonging to this token does not exist"
TokenIsInvalidOrSessionHasExpired = "The token is invalid or the session has expired"
UserEmailExist = "User with that email already exists"
YouAreNotLoggedIn = "You are not logged in"

[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."
