ServerStatusMethodNotAllowed = "Method not allowed!"
SavedSuccessfully = "Saved successfully!"
AccountIsBlocked = "Unfortunately, your account is blocked!" 
AccountIsDeleted = "Unfortunately, your account is blocked and will be deleted in 1 month!" 
AccountIsPending = "Your account is not yet activated! Please try again later..." 
AccountIsRejected = "Unfortunately, your account registration request has been rejected!"
RegisterUserConglaturation = "Congratulations! Your account has been successfully created!"
InvalidEmailOrPassword = "Invalid email or password"
CodeSuccessfullyAddeded = "Code successfully addeded"
YouAreNotLoggedIn = "You are not logged in"
TokenIsInvalidOrSessionHasExpired = "The token is invalid or the session has expired"
LogoutSuccessful = "Logout Successful"
TheUserBelongingToThisTokenNoLoggerExists = "The user belonging to this token does not exist"
CouldNotRefreshAccessToken = "Could not refresh access token"
SometingWentWrongServer = "Something went wrong on the server"
UserEmailExist = "User with that email already exists"
PasswordDoNotMatch = "Password do not match!"
InvalidOtpCode = "Invalid Otp Code!"
SubjectOtpCode = "Your verification code: {{.OtpCode}}"
MessageOtpCode = "Hello, <b>{{.Customer}}</b>!<br />Code: <b>{{.OtpCode}}</b>!<br />Copy it and paste it into the field for verification.<br />Don't show this code to anyone!<hr><small><i>Best regards, team HackStay!</small></i>"
ErrorAttemptExceeded = "Number of code entry attempts exceeded. Please come back later..."
HttpStatusForbidden = "You do not have access to perform this operation"
HelloPerson = "Hello {{.Name}}"
[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."
[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."

